<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>de.diddiz</groupId>
        <artifactId>logblock-parent</artifactId>
        <version>1.20.0.0-SNAPSHOT</version>
    </parent>
    <artifactId>logblock</artifactId>
    <name>LogBlock</name>
    <dependencies>
        <dependency>
            <groupId>de.diddiz</groupId>
            <artifactId>logblock-core</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>de.diddiz</groupId>
            <artifactId>logblock-spigot</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>de.diddiz</groupId>
            <artifactId>logblock-paper</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>
    <build>
        <finalName>LogBlock</finalName>
        <resources>
            <resource>
                <filtering>true</filtering>
                <directory>src/main/resources</directory>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>regex-property</id>
                        <goals>
                            <goal>regex-property</goal>
                        </goals>
                        <configuration>
                            <name>minecraft.plugin.version</name>
                            <value>${project.version} ${buildDescription}</value>
                            <regex>[0-9\.]+ \(.+\)</regex>
                            <replacement>${project.version}</replacement>
                            <failIfNoMatch>false</failIfNoMatch>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <relocations>
                                <relocation>
                                    <pattern>com.zaxxer.hikari</pattern>
                                    <shadedPattern>de.diddiz.lib.com.zaxxer.hikari</shadedPattern>
                                </relocation>
                            </relocations>
                            <filters>
                                <filter>
                                    <artifact>*:*</artifact>
                                    <excludes>
                                        <exclude>META-INF/*.SF</exclude>
                                        <exclude>META-INF/*.RSA</exclude>
                                        <exclude>META-INF/*.DSA</exclude>
                                    </excludes>
                                </filter>
                            </filters>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>de.diddiz</groupId>
                <artifactId>logblock-api-check</artifactId>
                <executions>
                    <execution>
                        <id>packaged-core-api-check</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>check</goal>
                        </goals>
                        <configuration>
                            <paperVersion>${paper.api.version}</paperVersion>
                            <classesDirectory>${project.build.directory}/LogBlock.jar</classesDirectory>
                            <coreArtifactId>logblock-core</coreArtifactId>
                            <checkPackaging>true</checkPackaging>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
                <executions>
                    <execution>
                        <id>copy-plugin-to-root</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <configuration>
                            <target>
                                <copy file="${project.build.directory}/LogBlock.jar" tofile="${maven.multiModuleProjectDirectory}/target/LogBlock.jar" />
                            </target>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
