<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>de.diddiz</groupId>
    <artifactId>logblock-parent</artifactId>
    <version>1.20.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>LogBlock</name>
    <description>Logs blocks.</description>
    <url>https://github.com/LogBlock/LogBlock</url>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <build.number>${buildNumber}</build.number>
        <spigot.api.version>26.3-R0.1-20261004.024323-9</spigot.api.version>
        <paper.api.version>26.3.build.157-beta</paper.api.version>
        <asm.version>9.10.1</asm.version>
        <maven.api.version>3.9.16</maven.api.version>
    </properties>
    <scm>
        <connection>scm:git:git://github.com/LogBlock/LogBlock.git</connection>
        <developerConnection>scm:git:ssh://git@github.com:LogBlock/LogBlock.git</developerConnection>
        <url>https://github.com/LogBlock/LogBlock</url>
    </scm>
    <ciManagement>
        <system>jenkins</system>
        <url>http://ci.md-5.net/job/LogBlock/</url>
    </ciManagement>
    <distributionManagement>
        <repository>
            <id>nexus</id>
            <name>Releases</name>
            <url>https://www.iani.de/nexus/content/repositories/releases/</url>
        </repository>
        <snapshotRepository>
            <id>nexus</id>
            <name>Snapshot</name>
            <url>https://www.iani.de/nexus/content/repositories/snapshots/</url>
        </snapshotRepository>
    </distributionManagement>
    <repositories>
        <repository>
            <id>spigot-repo</id>
            <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
        </repository>
        <repository>
            <id>sk89q-repo</id>
            <url>https://maven.enginehub.org/repo/</url>
        </repository>
        <repository>
            <id>brokkonaut-repo</id>
            <url>https://www.iani.de/nexus/content/groups/public/</url>
        </repository>
        <repository>
            <id>papermc</id>
            <url>https://repo.papermc.io/repository/maven-public/</url>
        </repository>
    </repositories>
    <profiles>
        <profile>
            <id>static_build_number</id>
            <activation>
                <property>
                    <name>!env.BUILD_NUMBER</name>
                </property>
            </activation>
            <properties>
                <buildNumber>0</buildNumber>
                <buildDescription>(manually compiled)</buildDescription>
            </properties>
        </profile>
        <profile>
            <id>dynamic_build_number</id>
            <activation>
                <property>
                    <name>env.BUILD_NUMBER</name>
                </property>
            </activation>
            <properties>
                <buildNumber>${env.BUILD_NUMBER}</buildNumber>
                <buildDescription>(build #${env.BUILD_NUMBER})</buildDescription>
            </properties>
        </profile>
    </profiles>
    <modules>
        <module>logblock-api-check</module>
        <module>logblock-core</module>
        <module>logblock-spigot</module>
        <module>logblock-paper</module>
        <module>logblock-plugin</module>
    </modules>
    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.15.0</version>
                    <configuration>
                        <release>25</release>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>3.5.6</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-plugin-plugin</artifactId>
                    <version>3.15.2</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-shade-plugin</artifactId>
                    <version>3.6.2</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-antrun-plugin</artifactId>
                    <version>3.2.0</version>
                </plugin>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>build-helper-maven-plugin</artifactId>
                    <version>3.5.0</version>
                </plugin>
                <plugin>
                    <groupId>de.diddiz</groupId>
                    <artifactId>logblock-api-check</artifactId>
                    <version>${project.version}</version>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>
